Aprb.Repo.start_link()
Application.ensure_all_started(:ex_machina)
Application.ensure_all_started(:calendar)
Logger.configure(level: :error)
ExUnit.configure seed: elem(:os.timestamp, 2)
ExUnit.start()
