ExUnit.start()
ExUnit.configure seed: elem(:os.timestamp, 2)
Aprb.Repo.start_link()
Ecto.Adapters.SQL.Sandbox.mode(Aprb.Repo, :auto)
Application.ensure_all_started(:ex_machina)
Application.ensure_all_started(:calendar)
