version: 2
jobs:
  test:
    docker:
      - image: artsy/hokusai:0.5.4
    steps:
      - add_ssh_keys
      - checkout
      - setup_remote_docker
      - run: mkdir -p ~/aprb/cover
      - run:
          name: Test
          command: hokusai test
      - run:
          name: Copy coverage artifacts
          command: docker cp hokusai_aprb_1:/app/cover ~/aprb
      - store_artifacts:
          path: ~/aprb/cover
  push:
    docker:
      - image: artsy/hokusai:0.5.4
    steps:
      - add_ssh_keys
      - checkout
      - setup_remote_docker
      - run:
          name: Push
          command: hokusai registry push --tag $CIRCLE_SHA1 --force --overwrite
  deploy:
    docker:
      - image: artsy/hokusai:0.5.4
    steps:
      - add_ssh_keys:
          fingerprints:
            - "05:c8:1f:ac:f8:a5:76:0e:d0:2d:52:0d:ef:12:2c:30"
      - checkout
      - run:
          name: Configure
          command: hokusai configure --kubectl-version 1.10.7 --s3-bucket artsy-citadel --s3-key k8s/config --platform linux
      - run:
          name: Deploy
          command: hokusai staging deploy $CIRCLE_SHA1
workflows:
  version: 2
  default:
    jobs:
      - test
      - push:
          context: hokusai
          filters:
            branches:
              only: master
          requires:
            - test
      - deploy:
          context: hokusai
          filters:
            branches:
              only: master
          requires:
            - push
