version: 2.1

orbs:
  hokusai: artsy/hokusai@0.7.0

jobs:
  test:
    docker:
      - image: artsy/hokusai
    steps:
      - add_ssh_keys
      - checkout
      - setup_remote_docker
      - run: mkdir -p ~/aprb/cover
      - run:
          name: Test
          command: hokusai test
      - run:
          name: Copy coverage artifacts
          command: docker cp hokusai_aprb_1:/app/cover ~/aprb
      - store_artifacts:
          path: ~/aprb/cover

not_staging_or_release: &not_staging_or_release
  filters:
    branches:
      ignore:
        - staging
        - release

only_master: &only_master
  context: hokusai
  filters:
    branches:
      only: master

only_release: &only_release
  context: hokusai
  filters:
    branches:
      only: release

workflows:
  default:
    jobs:
      # pre-staging
      - test:
          name: test
          <<: *not_staging_or_release

      # staging
      - hokusai/push:
          name: push-staging-image
          <<: *only_master
          requires:
            - test

      - hokusai/deploy-staging:
          <<: *only_master
          project-name: aprb
          requires:
            - push-staging-image

      # release
      - hokusai/deploy-production:
          <<: *only_release