source "https://api.berkshelf.com"

cookbook 'citadel', git: 'https://github.com/artsy/citadel.git', ref: 'v1.0.4'
cookbook 'artsy_base', git: 'git@github.com:artsy/infrastructure.git', tag: 'artsy_base-v0.1.3', rel: 'site-cookbooks/artsy_base'
cookbook 'artsy_apr', path: './site-cookbooks/artsy_apr'

cookbook 'nodejs', '= 2.4.4'

# fixing OpsWorks problem
cookbook 'ohai', '= 3.0.1'
