source 'https://rubygems.org'

ruby '2.2.2'

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

gem 'chef'
gem 'momentum', :git => 'git@github.com:artsy/momentum.git'
